### ISSUE TITLE
Versão com Typebot, n8n e GPT

### ISSUE THREAD

**Issue by palmeirarocha** [launcherbr/whaticketsaas-desatualizado#5]
Estamos com uma versão mais nova do whaticket, com integração com Typebot, n8n, openai e arquivos no bot.
Como está é uma versão comercializada por outra pessoa, não estamos liberando de forma aberta como está.
Quem tiver interesse, vou liberar o acesso privado ao nosso Github.

Valor R$ 40

Versão atual Whaticket Gold 4.7.2
https://plwdesign.online/produto/script-chatbot-multi-atendentes-e-multi-departamentos-para-whatsapp-business-2023/

* Futuras atualizações serão fornecidas.

**Comment by gabrielevo90** [comment]
Oi parceiro, tenho interesse em adquirir, te mandei msg tbm no insta
